# Generated by Django 4.1.7 on 2023-03-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_products_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
